### ISSUE TITLE
ModuleNotFoundError: No module named 'aiohttp' on MacBookPro M1 MAX running macOS Monterey

### ISSUE THREAD

**Issue by syntheticperson** [xch-gallery/nft-companion#6]
I tried to install nft-companion on my  MacBookPro M1 MAX running macOS Monterey.

Here is an error summary:

sh install.sh

...

INFO: pip is looking at multiple versions of singleton-utils to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement clvm-rs==0.1.15 (from chia-blockchain) (from versions: 0.1.0, 0.1.1, 0.1.2, 0.1.4, 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.1.10, 0.1.14, 0.1.16, 0.1.17, 0.1.19)
ERROR: No matching distribution found for clvm-rs==0.1.15

python3 nft.py create --help
Traceback (most recent call last):
  File "nft.py", line 5, in <module>
    import aiohttp
ModuleNotFoundError: No module named 'aiohttp'

Please find attached my stack trace.

Thanks

[nft-companion_error_log.txt](https://github.com/xch-gallery/nft-companion/files/7964524/nft-companion_error_log.txt)

**Comment by syntheticperson** [comment]
I tried to install on raspberry PI.
It finds the matching distribution found for clvm-rs.
However, it is getting the same error No module named 'aiohttp'
Next I'll try Windows.

**Comment by syntheticperson** [comment]
pip3 install aiohttp made the above error go away.

**Comment by syntheticperson** [comment]
I now get: 

pi@raspberrypi:~/nft-companion $ python3 nft.py create --name "Bud n' Spud: Gold" --uri "https://budnspud.s3.us-west-1.amazonaws.com/BudN_Spud_Gold.v03.png"
Traceback (most recent call last):
  File "nft.py", line 8, in <module>
    from blspy import PrivateKey, AugSchemeMPL, G2Element
ModuleNotFoundError: No module named 'blspy'

**Comment by syntheticperson** [comment]
When I try pip3 install blspy, I get the attached errors.
[InstallBlspyError.txt](https://github.com/xch-gallery/nft-companion/files/8147677/InstallBlspyError.txt)

**Comment by syntheticperson** [comment]
cmake was missing. I fixed this with:  
sudo apt install -y cmake
...
Successfully installed blspy-1.0.9

**Comment by syntheticperson** [comment]
I think I got all the dependent libraries installed.

When I try to create an NFT, now I'm getting:
SSL handshake failed on verifying the certificate.

Error log attached.

[nft_create_error.txt](https://github.com/xch-gallery/nft-companion/files/8147724/nft_create_error.txt)

**Comment by syntheticperson** [comment]
After multiple re-install attempts, I was finally able to get my wallet and nft companion installed.
So I'm closing this specific issue.
Thanks
